# Cargo dependency license policy — enforced in CI via `cargo deny check`.
# See docs/licensing.md for rationale and UI (npm) font licensing.

[graph]
all-features = true

[licenses]
version = 2
allow = [
  "Apache-2.0",
  "MIT",
  "BSD-2-Clause",
  "BSD-3-Clause",
  "ISC",
  "Zlib",
  "Unicode-3.0",
  "CC0-1.0",
  "0BSD",
]
confidence-threshold = 0.8
exceptions = []

[licenses.private]
ignore = false

[bans]
multiple-versions = "warn"
wildcards = "allow"

[sources]
unknown-registry = "deny"
unknown-git = "warn"